const CONSTANTES = {
  SCREEN: {
    width: 1024,
    height: 576
  },
  // PROJECTILES
  PROJECTILE_RADIUS: 5,
  PROJECTILE_SPEED: 5,
  // PLAYER
  PLAYER_SPEED: 5,
  PLAYER_ROTATION_SPEED: 5,
  PLAYER_RADIUS: 20
}

module.exports = CONSTANTES
